package br.jogoteca.system.application;

public enum Tela {
	LOGIN, CADASTRO, LOGINCADASTRO,
	PRINCIPALADMIN, CONSULTACLIENTES, 
	CONSULTAPEDIDOS, CRUDJOGOS, LISTADESEJOS, LISTAFAVORITOS,
	PRINCIPALUSUARIO, PERFILUSUARIO, PEDIDOSUSUARIO, PERFILJOGO,
	PEDIDOCOMPRA, PEDIDOALUGUEL, PAGAMENTO,
	CARRINHO, TELAX
}
